### ISSUE TITLE
Error: Cannot find module 'git-rev-sync'

### ISSUE THREAD

**Issue by lycasa** [lycasa/wheremap#1]
$ jake build
jake aborted.
Error: Cannot find module 'git-rev-sync'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
(See full trace by running task with --trace)

 npm install git-rev-sync --save

**Comment by m-annabi** [comment]
Npm install

**Comment by sasi1369** [comment]
npm install git-rev-sync

just run this cmd
